version: '3.3'

services:
  apig:
    container_name: "APIG_CONTAINER"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - URL_1=http://localhost/swagger
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - SwaggerSettings__ServiceName=APIG
    ports:
      - "5000:80"
